### ISSUE TITLE
doubleclick resets to default value

### ISSUE THREAD

**Issue by spunktsch** [AidaDSP/AIDA-X#11]

**Comment by falkTX** [comment]
I forgot to document this, but on DPF the expected behaviour is:
- ctrl + click to move slowly
- shift + click to reset to default

double-click is not ideal because it requires precise timing, which is a problem for some people

**Comment by falkTX** [comment]
Actually why not both.
Implemented in f32ee002fbbf957265b50438977af547268fcba0
