### ISSUE TITLE
VST3 produces high-pitched noise after a new model has been loaded

### ISSUE THREAD

**Issue by MaxPayne86** [AidaDSP/AIDA-X#2]
The noise persists and is present even if no audio input is provided

--

Useful Infos
- Windows 10
- Reaper DAW v6.70
- 48kHz, 256 buffer size, ASIO, default settings
- UMC404HD USB Soundcard

**Comment by falkTX** [comment]
is this anyhow similar to xsimd over-optimization on MOD units?

**Comment by spunktsch** [comment]
> is this anyhow similar to xsimd over-optimization on MOD units?

sounds very similar to the issue. Also VST2 has this problem. Its more of an heavy distorted output.

Infos

Windows 11
Reaper DAW v6.77
48kHz, Windows Audio

**Comment by falkTX** [comment]
We can try a build with eigen engine for comparison. will do that after finishing the current things

**Comment by falkTX** [comment]
@spunktsch this needs retesting please

**Comment by MaxPayne86** [comment]
Confirm re-tested on my setup.
