### ISSUE TITLE
Python error in model training

### ISSUE THREAD

**Issue by dabaldassi** [AidaDSP/AIDA-X#21]
Hi, 

I'm not sure if this is the right place to post this issue,
but I got a python error when training a model at step 2 in the google cloud.
![image](https://user-images.githubusercontent.com/34351698/233789555-4f8daeb8-bb6e-4711-9338-6ac711bae221.png)

**Comment by falkTX** [comment]
I see you posted in https://forum.mod.audio/t/mod-presents-the-aida-x-and-dives-into-neural-modelling/9465/45
that is a better place to discuss it, I tagged @MaxPayne86 as he is the one that will know about this.

my guess though is that this is related to the amount of channels on the audio files.
