### ISSUE TITLE
Input/Output meter

### ISSUE THREAD

**Issue by spunktsch** [AidaDSP/aida-x#3]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/1137715/228930740-b29347d0-dba0-4ae6-8333-f02573ef7d5f.png">

something like that.

**Comment by falkTX** [comment]
the standalone has button in there for enabling audio input, but maybe we can do it on each mouse click instead since it seems a bit pointless to have a button just for what is essential..

needs some discussion, it is intended that audio input is not enabled by default on a standalone, otherwise just opening can cause feedback loops to unsuspected users just randomly trying things out.

**Comment by falkTX** [comment]
for reference
![image](https://user-images.githubusercontent.com/1334853/228935092-c5e91638-cc95-4ae7-82fb-ef97783f915f.png)

**Comment by falkTX** [comment]
that is a bypass, not an on/off switch. this would make the tool behave differently on standalone vs plugin mode

**Comment by falkTX** [comment]
I realize it says on/off on the graphics, but the switch is never meant to really fully mute the audio.

an alternative is to have a little popup-like dialog message when launching the standalone, with some text regarding possible feedback loops and explaining the tool uses the default audio interface as set up in the OS system settings.
if we go for this, I would be quite happy to place some meters on the top left.
on the center for standalone I am still to add some buffer size options.

**Comment by spunktsch** [comment]
Common practice on most is to popup a config dialog the first time and have acess to it via geara icon.
<img width="326" alt="image" src="https://user-images.githubusercontent.com/1137715/229055799-e994a360-9450-4e9f-887e-b09b409bae3f.png">

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/1137715/229056166-b808bc47-e3de-45cd-899d-80d326754301.png">

**Comment by falkTX** [comment]
yes, but that is a bit too complex for the target audience. it should be just plug and play kinda deal.
I like the idea of settings button though, we can have it even as a kinda "show back of amp" fake mode where the graphics go away leaving only the bg color, then we place some more advanced options there (like the eq freqs)

then we can simply have the enable-input button be in the middle, but only when required. we can hide it after we know audio input is working

**Comment by falkTX** [comment]
Implemented in 33639cacd70f9af6341bdf49134191648da702a9

![image](https://user-images.githubusercontent.com/1334853/229301773-dd50000b-da93-4f24-be7f-b7da3a7f6070.png)
