### ISSUE TITLE
Plugin won't load LSTM-80 file. LSTM-40 works though.

### ISSUE THREAD

**Issue by 38github** [AidaDSP/AIDA-X#32]
I trained and exported the model and I assume the colab file managed to use the model since it could make a prediction audio sample. When I opened the json file in AIDA-X (x86_64 Linux) and the box then shows the name of the loaded model I chose but the sound is unchanged from the previous model. 

This is the file that will not load:
[wont_load_LSTM-80-0_ESR_0p0215.json.zip](https://github.com/AidaDSP/AIDA-X/files/12249035/wont_load_LSTM-80-0_ESR_0p0215.json.zip)

**Comment by falkTX** [comment]
the maximum size we set is 64, typically that is more than enough for everything.
we can easily add size 80, but curious on why you went with such a large model

**Comment by 38github** [comment]
> the maximum size we set is 64, typically that is more than enough for everything. we can easily add size 80, but curious on why you went with such a large model

Thank you for replying so quickly. Well, there are some amps, especially if boosted into extreme distortion, that can benefit from larger hidden_sizes. It is also interesting to see what can be achieved with unusual settings.

If I can hear a difference between 40 and 80 I don't know at this point but it will be interesting to know when/if it is compatible with AIDA-X.

**Comment by falkTX** [comment]
It can be easily be made compatible, let me just add that size in the next commit... just a matter of running a script

**Comment by falkTX** [comment]
ok should work with 005012ff7ad125b0dbc05407cceb6e9ab9eff78d

**Comment by 38github** [comment]
Thank you very much! I will compile it immediately and close this issue when I have played with it.

**Comment by 38github** [comment]
It works great! Thank you so much!
