### ISSUE TITLE
Possible to use more num_layers?

### ISSUE THREAD

**Issue by 38github** [AidaDSP/AIDA-X#34]
I trained a model using 3 num_layers which improved a fuzz sound from the default. Using default I got ESR 0.18 but by using 3 num_layers I got 0.10 and after one more round of training it went down to 0.08.

The problem is that the plugin can't use it correctly. It does load the model but the sound is very quiet and does not have much distortion.

Is it possible to enable more num_layers kind of like how you enabled larger hidden_sizes? 

3 num_layers file:
[_LSTM-40-0_ESR_0p0886.zip](https://github.com/AidaDSP/AIDA-X/files/12328141/_LSTM-40-0_ESR_0p0886.zip)

**Comment by MaxPayne86** [comment]
@38github yes it's definitely possible. Would you share your patches for https://github.com/AidaDSP/Automated-GuitarAmpModelling as well? I see your model still has 1 lstm layer. It could be modelToKeras.py needs to be adjusted too

**Comment by 38github** [comment]
All I have done for now is the following:
https://github.com/38github/Automated-GuitarAmpModelling/commit/946691a5a780bffabbf8ee31fafd8e6619f8bc33
https://github.com/38github/Automated-GuitarAmpModelling/commit/aadbf6adb026c22989a961efcd02cb1f7cf4ce26

Is it the part that generates the json file that needs modification?

**Comment by 38github** [comment]
I wish that I could help out more than this.

**Comment by MaxPayne86** [comment]
@38github I would need the original json file prior to invoking modelToKeras.py. This script needs to gather the number of rec layers from the model file, since atm it expects an input file with only one rec layer

**Comment by 38github** [comment]
Do you want me to train using the settings I used and then ignore exporting model and instead send you the best_model.json file?

**Comment by 38github** [comment]
I have tests that I have done with NAM and its LSTM implementation. I didn't try 1 num_layers though. Only 2 and 3.

[lstm_tests_2_num_layers_list.pdf](https://github.com/AidaDSP/AIDA-X/files/12896587/lstm_tests_2_num_layers_list.pdf)
[lstm_tests_3_num_layers_list.pdf](https://github.com/AidaDSP/AIDA-X/files/12896590/lstm_tests_3_num_layers_list.pdf)

Is AIDA-X using 1 num_layers by default?

**Comment by MaxPayne86** [comment]
Nice! I've seen also the companion thread that I will [here for reference](https://github.com/sdatkinson/neural-amp-modeler/issues/291#issuecomment-1758406936). I don't see particular issues for adding the support on runtime side (plugin). So to proceed stright away I need:

- model.json (produced when patience on val stops training)
- best_model.json (the best val loss)

if you prefer to input NAM model file format we will try to figure it out too ;)
