### ISSUE TITLE
CLAP plugin .json/.wav upload function doesn't work 

### ISSUE THREAD

**Issue by StevenRVE** [AidaDSP/aida-x#4]
Reproduction steps:
1. Open reaper
2. Insert new track
3. Load CLAP:AIDA-X (Aida DSP) plugin
4. Click on one the upload buttons 
![image](https://user-images.githubusercontent.com/42948605/229225330-5a63df46-f248-41e7-b99f-998821da22d1.png)
5. Now you see nothing happens

System info:
- Windows 10
- Reaper v6.78
- Komplete Audio 6 MK2 audio interface
- ASIO: 44.1Hz, 512 samples, default settings

**Comment by falkTX** [comment]
Should be fixed in e7c6327054b26602d40a7827efa98213c5e1bd82

**Comment by StevenRVE** [comment]
Tested and confirmed, fixed it is.
