### ISSUE TITLE
LV2 GUI takes almost all CPU

### ISSUE THREAD

**Issue by jofemodo** [AidaDSP/AIDA-X#41]
While testing on zynthian platform (linux arm64 + LV2), we discovered that GUI seems to use almost all available CPU, until reaching 75-80% and more. When disabling the GUI (LV2 can run GUI-less) CPU usage is very low, while audio processing is still running without issues, smoothly. We tested with several models and IRs, same results.

+ Platform: Zynthian (RPi5 + linux arm64 + LV2)
+ OS version: Raspberry Pi OS (Debian Bookworm)
+ GUI running via VNC.

**Comment by riban-bw** [comment]
This seems to only occur if the GUI is running on a display that is exposed via VNC. Running the GUI on a physical monitor does not trigger the problem. Zynthian exposes many LV2 GUI via VNC without any suffering this issue so it is a problem with this particular plugin. We are using the current [stable precompiled 1.1.0 release](https://github.com/AidaDSP/AIDA-X/releases/download/1.1.0/AIDA-X-1.1.0-linux-arm64.tar.xz).

**Comment by spunktsch** [comment]
better use the lv2 version: https://github.com/AidaDSP/aidadsp-lv2

**Comment by riban-bw** [comment]
This is a bug report against the precompiled release version of the LV2 from [here](https://github.com/AidaDSP/AIDA-X/releases/tag/1.1.0). If this "stable release" is not supported, maybe it should not be built and offered to users?

**Comment by riban-bw** [comment]
> better use the lv2 version: https://github.com/AidaDSP/aidadsp-lv2

That is actually a fork that provides a plugin for the mod-ui environment. Although it uses the same technology as LV2, the build process does not create a full LV2 bundle and the GUI is very different and non-standard. I compiled aidadsp-lv2 but it is not suitable.

Zynthian is far more like a DAW. It hosts the LV2 as a plugin (both with and without GUI (headless)) and needs a proper LV2 bundle. There is a proper LV2 bunder created by AIDA-X and it is provided by the stable releases. This bug report specifically refers to the GUI of the AIDA-X stable release which, under some conditions consumes almost all of the CPU on all available cores. Running without GUI results in very low CPU usage - so the GUI code appears to be causing a problem.

**Comment by spunktsch** [comment]
this is likley caused by some combination of vnc and DFP maybe @falkTX can see to that issues.
