### ISSUE TITLE
LV2 monitors doesn't work when running GUI-less

### ISSUE THREAD

**Issue by jofemodo** [AidaDSP/AIDA-X#42]
When running LV2 GUI-less, monitor ports are not refreshed. When running the GUI, they work normally. Monitors should be sent also when GUI is not enabled, or at least, have an option to enable/disable monitors.

Platform: Zynthian (RPi5 + linux arm64 + LV2)
OS version: Raspberry Pi OS (Debian Bookworm)

**Comment by riban-bw** [comment]
It looks like meter is not getting reset. I think the GUI resets the meters during idle times but I cannot see a way to do this from a LV2 client. Maybe if the client can set state "reset-meters" it could reset the meters but I can't see how to do that in jalv.

**Comment by spunktsch** [comment]
you might be better off to using the lv2 plugin directly.
See: https://github.com/AidaDSP/aidadsp-lv2
