### ISSUE TITLE
Model Export failing on AIDA X Model Trainer

### ISSUE THREAD

**Issue by jotagenazar** [AidaDSP/AIDA-X#43]
When trying to export a trained model using the AIDA X Model Trainer on Google Colab, copyfile is not being able to find "model_keras.json" under Results folder. Something must have changed in the keras library. Here's the full Model Export log, and I got the same error for every model I tried to train.

Generating model file: Marshall 2525H v3_LSTM-12-0.json
/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1724067933.220409    4691 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1724067933.271304    4691 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1724067933.271658    4691 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1724067933.277983    4691 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1724067933.278210    4691 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1724067933.278427    4691 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1724067933.470082    4691 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1724067933.470381    4691 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1724067933.470589    4691 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
Traceback (most recent call last):
  File "/content/Automated-GuitarAmpModelling/modelToKeras.py", line 85, in <module>
    lstm_layer = keras.layers.LSTM(hidden_size, activation=None, weights=lstm_weights, return_sequences=True, recurrent_activation=None, use_bias=bias_fl, unit_forget_bias=False)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/lstm.py", line 486, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py", line 204, in __init__
    super().__init__(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/layers/layer.py", line 266, in __init__
    raise ValueError(
ValueError: Unrecognized keyword arguments passed to LSTM: {'weights': [array([[ 6.60592541e-02, -1.85463473e-01,  2.91573942e-01,
         2.45860592e-01, -8.15418661e-02,  7.75152892e-02,
         4.01835190e-03, -3.27668823e-02, -1.52905071e-02,
        -1.45363808e-01, -9.04606134e-02,  3.45285572e-02,
        -3.77460793e-02, -4.45241779e-02,  3.22128199e-02,
         9.36680287e-02, -1.01195216e-01, -1.44828875e-02,
         8.39575939e-03, -4.28125896e-02,  1.35291785e-01,
        -1.90442756e-01, -8.83284956e-02,  2.01224741e-02,
        -5.69425774e+00,  6.10955298e-01,  3.69630516e-01,
        -4.53105211e-01, -1.62291169e-01, -4.09498028e-02,
         3.07930613e+00,  1.71425954e-01,  6.46085620e-01,
         3.39670002e-01,  1.64213642e-01,  5.42318523e-01,
        -9.05587450e-02, -5.54878175e-01,  6.56083785e-03,
         4.55473512e-01, -1.06242314e-01, -1.52269402e-03,
         8.10337160e-03, -2.28969902e-02,  1.99903771e-02,
        -1.81676179e-01, -5.97323552e-02,  4.64963801e-02]]), array([[ 4.61226791e-01, -2.40906253e-01,  6.05380177e-01,
         1.16820939e-01,  5.67865930e-02,  6.10170094e-03,
        -1.46325203e-02, -5.15195541e-02, -1.14406407e-01,
         3.26480716e-01, -4.36199009e-01,  1.18167043e-01,
         1.11368112e-01,  3.13587457e-01, -1.62575200e-01,
         1.54996514e-01, -2.24014178e-01,  4.17284481e-02,
         1.19663797e-01, -9.80473496e-03,  4.42907244e-01,
         1.30282700e-01, -7.82935798e-01,  1.63571745e-01,
         6.77698851e-01, -6.69380426e-01, -1.49365294e+00,
         4.14951921e-01,  4.57340002e-01,  1.48942161e+00,
         4.22639191e-01, -1.15596123e-01, -1.82948947e+00,
        -5.18981181e-03,  2.61114448e-01,  3.29079628e-01,
        -8.92767727e-01,  6.73966408e-02, -7.98407122e-02,
        -2.47330695e-01, -6.33482216e-03,  1.20702326e-01,
        -1.86460763e-02,  5.05711697e-02, -6.03230819e-02,
        -7.73401931e-02,  3.88177097e-01, -3.53364736e-01],
       [ 2.68348038e-01,  3.86285424e-01,  6.14301443e-01,
         2.10623696e-01,  2.31220126e-01,  5.65186381e-01,
        -2.66893506e-01, -3.58372219e-02,  1.42851910e-02,
         1.63053274e-01, -1.75054803e-01, -3.47995223e-03,
        -4.18091901e-02, -4.90624905e-01,  1.92745879e-01,
         3.43767345e-01, -8.20410028e-02, -4.87219542e-01,
         6.00438356e-01, -5.47111593e-02,  5.86831093e-01,
        -1.06205009e-01,  1.98420081e-02, -3.19051027e-01,
         1.77511740e+00,  2.99270898e-01,  2.32696861e-01,
        -1.37289360e-01, -1.62240386e-01, -2.90533602e-01,
        -1.04820788e+00, -5.55899888e-02, -1.11902855e-01,
         1.14502001e+00, -4.81374294e-01, -1.05531782e-01,
         4.17224020e-01, -4.97067213e-01,  8.79088491e-02,
         8.46434683e-02, -7.49148726e-02, -1.45933524e-01,
        -2.70585120e-01, -2.60675758e-01, -2.38312185e-01,
        -1.82233572e-01, -4.10690397e-01, -2.01784030e-01],
       [ 5.89568794e-01, -7.87080765e-01,  3.35695684e-01,
        -5.12516618e-01, -5.12554422e-02,  6.08857870e-02,
         2.82333255e-01,  6.24148138e-02,  2.11513609e-01,
        -5.67948818e-01,  3.89805675e-01, -4.27485555e-01,
        -6.94954768e-02,  3.26032788e-01, -1.41451374e-01,
         4.54128206e-01, -1.51648954e-01,  4.54252481e-01,
         4.05766010e-01,  6.53226078e-02,  3.49291801e-01,
        -2.62949079e-01,  8.45123470e-01,  2.65273899e-01,
         3.57759356e-01,  1.96084186e-01, -5.40993176e-02,
         9.93377790e-02,  1.45545542e-01,  6.38503879e-02,
        -1.53166689e-02, -1.58295393e-01, -8.63298681e-03,
         5.13001457e-02, -6.11867487e-01, -2.24494133e-02,
         1.25089443e+00, -1.67813361e-01,  1.44501761e-01,
        -1.73303619e-01, -2.38038064e-03,  7.58230314e-02,
         2.91039437e-01,  2.23119706e-01,  3.30205709e-01,
        -1.93059638e-01,  2.10678101e-01,  1.83617860e-01],
       [-1.32507468e-02, -3.20242375e-01,  1.76866055e-01,
         9.70790908e-02,  2.22372249e-01, -1.92024082e-01,
        -1.81852892e-01, -3.95288952e-02,  1.14302330e-01,
        -2.50763535e-01, -2.15243563e-01, -2.93799758e-01,
        -3.10968570e-02, -6.89411104e-01,  1.56073496e-01,
         2.23422334e-01,  4.94480319e-02, -3.45600903e-01,
         5.19268274e-01, -7.46295899e-02,  2.22573072e-01,
        -1.90256447e-01,  1.95945680e-01, -3.74794394e-01,
        -2.03513074e+00,  1.11753158e-01,  2.29699358e-01,
         1.75933763e-01,  3.31314206e-01,  1.33674055e-01,
         1.04639030e+00, -4.12202766e-03,  8.27392489e-02,
        -1.41308248e-01, -2.38736674e-01, -2.58068979e-01,
         3.82403344e-01,  3.57178302e-04,  1.53809413e-01,
        -2.80600667e-01,  1.05340481e-01,  1.55445576e-01,
        -1.80247560e-01, -6.51116893e-02, -9.31010675e-03,
        -2.86252707e-01, -2.56996453e-01, -1.56428829e-01],
       [-1.80147290e-01,  5.17186701e-01,  2.35592157e-01,
        -1.04960181e-01, -2.96075512e-02, -5.07685579e-02,
        -4.70234118e-02,  2.72842050e-02, -9.43444520e-02,
         2.94294775e-01, -7.94412270e-02,  3.83293182e-01,
         1.88697994e-01, -1.09601714e-01,  4.95446473e-02,
         1.68895274e-01, -1.81216091e-01,  1.00019164e-01,
         4.84871790e-02, -1.86938439e-02,  5.18973731e-02,
         3.14889133e-01,  1.04307227e-01,  3.00713807e-01,
        -1.86457172e-01, -1.62624195e-01, -2.67225988e-02,
         1.13832995e-01,  3.82153779e-01,  5.72146587e-02,
         8.56721103e-02, -2.91494101e-01, -1.37124890e-02,
         4.73695137e-02,  1.10462392e-02, -2.83118486e-01,
         2.39602342e-01,  5.15701482e-03,  1.82519078e-01,
         2.85490036e-01,  8.86354819e-02,  6.79471642e-02,
        -4.78321388e-02, -1.02486491e-01, -1.36848986e-01,
         3.19234341e-01, -5.75380214e-02, -6.58173487e-02],
       [ 1.03419495e-03,  6.03067338e-01,  2.94188410e-01,
        -3.77986990e-02,  3.95052075e-01, -5.59596300e-01,
         1.29064709e-01,  9.81130525e-02,  1.52023315e-01,
         1.61021322e-01, -2.71247059e-01, -1.66958034e-01,
        -1.85291335e-01, -1.76844850e-01, -2.50963926e-01,
         2.57682651e-01,  3.70079368e-01,  1.22855276e-01,
         3.95851195e-01,  1.48340791e-01, -8.69267955e-02,
         4.50667702e-02,  2.62053639e-01, -3.81544977e-01,
        -6.30430400e-01, -1.57150358e-01,  5.52617610e-02,
        -3.99804153e-02,  1.27110392e-01,  1.78263530e-01,
         3.53460729e-01, -9.40515697e-02, -3.47592443e-01,
         1.97480455e-01, -2.66631961e-01,  1.24950774e-01,
         3.71847987e-01,  1.70650989e-01,  1.17738046e-01,
        -6.67255670e-02,  3.28855276e-01, -1.85213685e-01,
         1.28980145e-01,  2.52014175e-02,  7.37071335e-02,
         6.28548115e-02, -1.13061909e-03,  2.91710105e-02],
       [ 4.45558466e-02, -4.99581367e-01, -6.59751713e-01,
         8.34360063e-01, -1.44802809e-01, -3.81496102e-01,
         2.25782469e-02,  9.48724058e-03,  2.13505164e-01,
         4.93929416e-01, -9.59003568e-01,  8.83508660e-03,
         8.08280185e-02, -2.81544160e-02,  2.34897137e-01,
         4.02775928e-02, -2.64619887e-01,  1.62943408e-01,
        -9.22981277e-02, -9.54335108e-02, -5.74817657e-01,
         4.56787705e-01, -2.85445243e-01,  1.78173542e-01,
        -8.25902343e-01,  1.60451587e-02,  1.42843306e+00,
        -3.59478414e-01, -2.96276450e-01,  3.44120622e-01,
        -2.20488250e-01,  2.82146215e-01,  1.56948030e+00,
         2.11353034e-01, -9.22737122e-01,  3.16810161e-01,
         2.08430395e-01, -3.92616183e-01, -2.62987148e-02,
         6.82239473e-01, -9.57572907e-02, -3.54714304e-01,
         2.31135935e-02,  8.22603554e-02,  4.12408412e-02,
         4.13203269e-01, -3.22374880e-01,  2.42616370e-01],
       [-9.90536034e-01,  5.82603753e-01, -2.87570000e-01,
         4.63988751e-01,  1.46001885e-02,  6.18988574e-01,
        -5.89514613e-01, -8.46920237e-02, -3.27012390e-01,
        -1.59927860e-01, -2.68385500e-01,  4.88308251e-01,
         3.10778052e-01, -7.76193738e-01, -1.70858964e-01,
        -8.80374849e-01, -6.00425541e-01, -1.12227547e+00,
         9.37738866e-02, -6.36347950e-01,  1.62625551e-01,
        -2.17668235e-01, -1.18895859e-01, -5.04544497e-01,
         2.03855455e-01,  2.54442483e-01, -1.92700520e-01,
        -1.18801676e-01, -9.70103890e-02, -9.68527049e-03,
         1.60421371e-01, -4.48321961e-02,  1.83906749e-01,
         1.62840962e-01,  1.44758537e-01, -2.01143861e-01,
        -6.63763821e-01, -2.05424488e-01, -4.95211661e-01,
        -3.07125747e-01, -2.34934896e-01, -1.69462562e-01,
        -5.89946806e-01, -5.66674173e-01, -4.15558338e-01,
        -4.49795604e-01, -5.49060047e-01, -2.78803051e-01],
       [-1.16071165e+00,  9.03224349e-01, -3.36169563e-02,
         9.43546891e-01,  1.09126382e-01,  1.11339137e-01,
        -2.10865989e-01,  1.25138313e-01, -5.26266396e-01,
         9.02154371e-02,  7.22615302e-01,  1.75027460e-01,
         2.04043984e-01, -9.90352452e-01, -6.33946359e-02,
        -5.83281159e-01,  9.58691612e-02, -6.60574555e-01,
        -4.90519136e-01, -2.25108236e-01,  9.75103378e-02,
         3.52283627e-01,  4.68620062e-01, -4.47067738e-01,
         1.27584711e-01, -3.24086010e-01, -6.51396453e-01,
        -1.08887523e-01,  1.44662455e-01,  1.65997043e-01,
        -8.99242908e-02,  7.89381862e-02, -2.17119679e-01,
        -3.56539965e-01, -8.12239796e-02,  3.38503510e-01,
        -5.33539653e-01, -6.53402209e-01, -3.39223772e-01,
         6.20669648e-02, -2.85855860e-01,  9.23516080e-02,
        -2.00305611e-01, -3.71698350e-01, -3.72630060e-01,
        -2.70848304e-01, -4.91905034e-01, -7.06404373e-02],
       [ 4.21522200e-01, -4.02529567e-01,  4.55702752e-01,
        -4.36242074e-01,  1.44225955e-02, -2.18780562e-01,
         1.52469516e-01, -1.60747021e-01,  4.68674451e-01,
        -9.32001397e-02, -3.20517272e-01, -1.43228173e-01,
        -4.24981266e-01,  8.13461898e-04, -2.18734413e-01,
         2.60091454e-01,  1.15449592e-01,  2.21758172e-01,
         3.94038498e-01,  1.06940702e-01,  2.81764209e-01,
        -5.91017902e-01, -9.74345505e-02,  1.18112467e-01,
         1.61329985e+00, -5.22767127e-01, -1.13352828e-01,
         8.44908136e-05,  4.19673920e-02,  3.35106373e-01,
        -7.68410683e-01,  1.63737729e-01, -5.56097746e-01,
         5.48147224e-02, -1.62312567e-01, -1.60987720e-01,
         2.15854362e-01, -1.08879060e-01,  2.24448547e-01,
         9.81442556e-02,  8.38338658e-02, -3.66631411e-02,
         1.49490103e-01,  1.25651896e-01,  2.59528548e-01,
        -1.80498928e-01, -1.87790021e-01,  3.13433886e-01],
       [-3.15999269e-01,  4.68059510e-01, -2.38489419e-01,
         8.58572245e-01,  4.88687605e-02,  6.79692149e-01,
        -3.44574213e-01, -1.06863476e-01, -2.99042642e-01,
         3.01113784e-01, -1.48559526e-01,  6.22145474e-01,
         4.20434207e-01, -4.06101733e-01, -2.04040930e-01,
        -5.13760149e-01, -2.76575834e-01, -7.88653672e-01,
        -7.78388306e-02, -3.87685895e-01,  4.56359126e-02,
        -3.73565108e-02,  7.87654950e-04, -1.09876484e-01,
        -6.11882396e-02, -3.01678509e-01,  6.10449575e-02,
         6.65598586e-02, -2.47797981e-01,  3.62675309e-01,
         3.82116556e-01,  4.59754705e-01,  3.31139803e-01,
         8.74508247e-02,  3.07155281e-01, -1.63290314e-02,
        -1.81000993e-01,  3.73865485e-01, -3.15261275e-01,
        -1.27905384e-01, -1.16187282e-01,  1.93175729e-02,
        -3.63055587e-01, -1.15039326e-01, -4.13512796e-01,
        -1.68770358e-01, -3.40710789e-01,  1.43624917e-01],
       [-5.45341134e-01,  5.32988906e-01, -2.93331981e-01,
         4.96661216e-01,  7.33416229e-02,  2.48613700e-01,
        -1.86547220e-01, -2.29040487e-03, -4.06360626e-01,
         3.13706219e-01,  2.49063656e-01,  3.30993980e-01,
         3.97334069e-01, -4.89697486e-01, -1.05057932e-01,
        -3.66962463e-01, -3.80559303e-02, -7.62445211e-01,
        -4.12228465e-01, -2.59577304e-01,  1.34376183e-01,
         5.28003991e-01,  2.63698995e-02, -2.00126290e-01,
         8.87245476e-01, -2.28371983e-03,  2.10676506e-01,
        -2.14573741e-01,  5.09709597e-01, -2.15453744e-01,
        -3.32467049e-01, -2.17204317e-01, -2.29003280e-01,
        -8.47596154e-02,  2.32078254e-01,  1.07179366e-01,
        -6.67161286e-01, -7.91375712e-02, -3.02543759e-01,
         1.06467173e-01, -2.47624889e-02, -1.20377392e-02,
        -1.86551407e-01, -1.94672883e-01, -3.47945333e-01,
         2.84872711e-01,  6.28903210e-02, -1.20285228e-01]]), array([ 3.09065819e-01, -1.75406361e+00,  1.15312237e-01, -1.21982563e+00,
       -3.72281224e-01, -2.14874065e+00,  1.40862679e+00, -1.24494154e-01,
        1.11880285e+00,  4.26961139e-01, -8.04183055e-02, -2.62370050e-01,
       -1.23662323e+00,  2.73012185e+00,  1.06651843e+00,  2.30255985e+00,
        9.44859415e-01,  3.00386608e+00, -3.66155624e-01,  1.43571973e+00,
        1.29987359e-01,  6.04844213e-01,  3.93766724e-03,  1.39728677e+00,
        3.32338378e-01, -7.54603967e-02, -4.62315977e-04, -3.34651105e-01,
       -4.73896638e-02,  3.13307643e-02,  1.53987933e-01, -3.57018888e-01,
       -1.47062145e-01,  8.74615610e-01, -4.23204318e-01, -4.17374730e-01,
       -4.65167493e-01,  1.23820597e+00,  1.00768620e+00,  8.98364484e-01,
        2.38462955e-01,  5.19480020e-01,  1.41734242e+00,  1.11267877e+00,
        1.38636220e+00,  1.00698191e+00,  6.67873859e-01,  1.00193769e+00])]}

---------------------------------------------------------------------------

FileNotFoundError                         Traceback (most recent call last)

[<ipython-input-4-295803fc25b4>](https://localhost:8080/#) in <cell line: 18>()
     16 get_ipython().system('python3 modelToKeras.py -lm "$model_path"')
     17 
---> 18 shutil.copyfile(os.path.join(model_dir, 'model_keras.json'), os.path.join('/content', os.path.split(model_dir)[-1]+'.json'))
     19 files.download(os.path.join('/content', model_filename))
     20 

[/usr/lib/python3.10/shutil.py](https://localhost:8080/#) in copyfile(src, dst, follow_symlinks)
    252         os.symlink(os.readlink(src), dst)
    253     else:
--> 254         with open(src, 'rb') as fsrc:
    255             try:
    256                 with open(dst, 'wb') as fdst:

FileNotFoundError: [Errno 2] No such file or directory: '/content/Automated-GuitarAmpModelling/Results/Marshall 2525H v3_LSTM-12-0/model_keras.json'

**Comment by MaxPayne86** [comment]
Issue solved with https://github.com/AidaDSP/Automated-GuitarAmpModelling/issues/8
