### ISSUE TITLE
VST, VST3, LV2 crashes when uploading Cab Sim

### ISSUE THREAD

**Issue by StevenRVE** [AidaDSP/aida-x#6]
Reproduction steps:
1. Open reaper
2. Insert new track
3. Click FX
4. Click Add
5. Select either:
- VST:AIDA-X (Aida DSP) (mono) plugin
- VST3:AIDA-X (Aida DSP) (mono) plugin
- LV2:AIDA-X (Aida DSP) (Mono) plugin
7. Click 
![image](https://user-images.githubusercontent.com/42948605/229226948-36d07fa5-70c2-427c-9cfe-ae10af6ab61e.png)
8. Select .wav IR file to upload (I've tried with multiple IR files and the behavior is the same)
9. Now you see that reaper either freezes and then crashes or crashes instantly

System info:
- Windows 10
- Reaper v6.78
- Komplete Audio 6 MK2 audio interface
- ASIO: 44.1kHz, 512 samples, default settings

**Comment by falkTX** [comment]
could it be due to resampling? does anything change if the host sample rate matches the file sample rate?

**Comment by StevenRVE** [comment]
I tested it again with ASIO settings 48kHz, 256 samples to match the file sample rate and it still crashed

**Comment by falkTX** [comment]
are you able to upload the file here? or send me over the MOD spaces chat if not shareable publicly.
wondering if this is related to the file itself, or the overall build. obviously some file loading does work, otherwise the plugin would crash on start.

another related question: does the filename to this file contain any non-ascii characters?

**Comment by StevenRVE** [comment]
I used these IR Cabinet files:
[IR-cabinet-files.zip](https://github.com/AidaDSP/aida-x/files/11126971/IR-cabinet-files.zip)

I also just now tested with some IR reverb .flac files and those worked without crashing. Also some other .wav did work without crashing, so it might that these IR Cabinet files produce the issue.

**Comment by falkTX** [comment]
Can reproduce the crash with those files.
Seems to be the same issue reported in https://github.com/DISTRHO/OneKnob-Series/issues/7

**Comment by falkTX** [comment]
Should be fixed in 640dde027fa003c2d87f9ecb05b8faed7beca76d

**Comment by StevenRVE** [comment]
I found another IR cabinet file that causes Reaper to crash:
[IR-cabinet-crash-file.zip](https://github.com/AidaDSP/aida-x/files/11127355/IR-cabinet-crash-file.zip)

All my other IR cab files now work without crashes

**Comment by falkTX** [comment]
Nice one! there was a memory leak and bad behaviour when loading non-mono cabinet files.
Fixed in 0be85c2706b630670a202c3db4b646056a0d82d4

**Comment by StevenRVE** [comment]
Confirmed
