### ISSUE TITLE
VST, VST3, LV2 produce noise tick after minimizing and maximizing Reaper window

### ISSUE THREAD

**Issue by StevenRVE** [AidaDSP/aida-x#7]
Reproduction steps:
1. Open reaper
2. Insert new track
3. Click FX
4. Click Add
5. Select either:
- VST:AIDA-X (Aida DSP) (mono) plugin
- VST3:AIDA-X (Aida DSP) (mono) plugin
- LV2:AIDA-X (Aida DSP) (Mono) plugin
7. Minimize the Reaper window
8. Maximize the Reaper window
9. Now you hear a noise tick

System info:
- Windows 10
- Reaper v6.78
- Komplete Audio 6 MK2 audio interface
- ASIO: 44.1Hz, 512 samples, default settings

**Comment by falkTX** [comment]
please upload a sound sample of the click

**Comment by StevenRVE** [comment]
Here ya go:
https://drive.google.com/file/d/1mK6TVQF39IhyKmw9bPTQ28xv6zbuagn3/view?usp=sharing

Extra info:
- Tick did not happen while recording in Reaper so I made a screen capture using OBS

**Comment by falkTX** [comment]
is there anything special reaper is doing here? does it stop the audio if you minimize the window or something?

**Comment by falkTX** [comment]
Seems to be related to deactivating and activating the plugin again.
Should be fixed in 29b2fed30828ab04170e52fe6841ccac580d7c0d please confirm.

**Comment by StevenRVE** [comment]
Confirmed, closing ticket.
